-- MySQL Script generated by MySQL Workbench
-- Thu Mar 20 12:16:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PayMyBuddy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PayMyBuddy` ;

-- -----------------------------------------------------
-- Schema PayMyBuddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PayMyBuddy` DEFAULT CHARACTER SET utf8 ;
USE `PayMyBuddy` ;

-- -----------------------------------------------------
-- Table `PayMyBuddy`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PayMyBuddy`.`User` ;

CREATE TABLE IF NOT EXISTS `PayMyBuddy`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PayMyBuddy`.`Transation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PayMyBuddy`.`Transation` ;

CREATE TABLE IF NOT EXISTS `PayMyBuddy`.`Transation` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `amount` INT NOT NULL,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Transation_User1_idx` (`sender_id` ASC) VISIBLE,
  INDEX `fk_Transation_User2_idx` (`receiver_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transation_User1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `PayMyBuddy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transation_User2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `PayMyBuddy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PayMyBuddy`.`Connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PayMyBuddy`.`Connections` ;

CREATE TABLE IF NOT EXISTS `PayMyBuddy`.`Connections` (
  `User_id` INT NOT NULL,
  `connectionUser_id` INT NOT NULL,
  INDEX `fk_User_has_User_User1_idx` (`connectionUser_id` ASC) VISIBLE,
  INDEX `fk_User_has_User_User_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_User_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `PayMyBuddy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_User_User1`
    FOREIGN KEY (`connectionUser_id`)
    REFERENCES `PayMyBuddy`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
