#
# Will start all docker constructions with MySQL
# 
# Password and network ports are handled in .env file
#
# IMPORTANT: Under Windows, it is VERY important to install a WSL 2 Distro and enable IT
#            See https://learn.microsoft.com/fr-fr/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package

version: "3.9"
services:
  mysql:
    image: mysql:8.0.32
    restart: unless-stopped
    env_file: ./.env
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=PayMyBuddy
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_USER_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - type: bind
        source: ./data.sql
        target: /docker-entrypoint-initdb.d/setup.sql
        read_only: true
      - type: volume
        source: vol_mysql
        target: /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - $PMA_LOCAL_PORT:$PMA_DOCKER_PORT
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=$DB_DOCKER_PORT
      - PMA_USER=root
      - PMA_PASSWORD=$DB_ROOT_PASSWORD
      - PMA_ARBITRARY=1

volumes:
  vol_mysql:

#
# Run all  : docker-compose up --build
# Stop all : docker-compose down
# Stop all and delte all img : docker-compose down --rmi all
#
